name: kilat
description: Priority-based Schedule Manager.
# Original codename: kilat
# Changed to: prism
# Created by: Jordan Valentino Lomanto

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.2+9

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # inject:
  #   path: ./injection/inject.dart/package/inject
  collection: ^1.14.11
  date_util: ^0.1.4
  flutter_slidable: ^0.5.3
  flutter_clean_calendar: ^1.0.1
  flutter_icons: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^1.2.3
  http: ^0.12.0+2
  intl: ^0.15.0
  rxdart: ^0.22.6
  shared_preferences: ^0.5.6
  table_calendar: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_cupertino_localizations: ^1.0.1

dependency_overrides:
  intl: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # build_runner: ^1.0.0
  # inject_generator:
  #   path: ./injection/inject.dart/package/inject_generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - resources/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    # For brand
    - family: FredokaOne
      fonts:
        - asset: resources/fonts/FredokaOne/FredokaOne-Regular.ttf
    # For texts
    - family: Raleway
      fonts:
        - asset: resources/fonts/Raleway/Raleway-Regular.ttf
        - asset: resources/fonts/Raleway/Raleway-RegularItalic.ttf
          style: italic
        - asset: resources/fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: resources/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: resources/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: resources/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: resources/fonts/Raleway/Raleway-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: resources/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: resources/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/Raleway/Raleway-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: resources/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: resources/fonts/Raleway/Raleway-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: resources/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: resources/fonts/Raleway/Raleway-Black.ttf
          weight: 900
    - family: Comfortaa
      fonts:
        - asset: resources/fonts/Comfortaa/Comfortaa-Regular.ttf
        - asset: resources/fonts/Comfortaa/Comfortaa-Light.ttf
          weight: 200
        - asset: resources/fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: resources/fonts/Comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: resources/fonts/Comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/Comfortaa/Comfortaa-Bold.ttf
          weight: 700
    # For numerics
    - family: NovaSquare
      fonts:
        - asset: resources/fonts/NovaSquare/NovaSquare-Regular.ttf
